### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by jaimebayes** [lucashadfield/speck#2]
Hi, 

I found this AttributeError when I try to run on google colaboratory after installing speck-0.2.0
`pip install speck`
Installing collected packages: speck
Successfully installed speck-0.2.0

  `import speck`
File` "/usr/local/lib/python3.6/dist-packages/speck/matcher.py", line 33
    raise AttributeError, "No matcher found for '%s'" % name
                        ^
SyntaxError: invalid syntax

Any advice to fix it?

Thanks in advance, JL

**Comment by lucashadfield** [comment]
That's not my package, mine isn't on pypi (yet). To install run: 
`pip install git+https://github.com/lucashadfield/speck.git`

which will clone the github repo and install it.

**Comment by jaimebayes** [comment]
> That's not my package, mine isn't on pypi (yet). To install run:
> `pip install git+https://github.com/lucashadfield/speck.git`
> 
> which will clone the github repo and install it.

Sorry, I confused them. 
The import works now, but when I try it using a personal file (jpg), it show a blanck image as result, then I run your other examples and it shows blank images too.
What could go wrong this time?
Thanks in advance, JL

**Comment by jaimebayes** [comment]
Wait...It run well now...sorry again.
Congrats for this interesting app, i will continue using it.
Thanks, JL
