### ISSUE TITLE
Name errors

### ISSUE THREAD

**Issue by jaimebayes** [lucashadfield/speck#3]
Hi, 

I am very excited about this image edition app.
It works really well, but the code for image 4 and 6 generates these name errors, such as:

NameError: name 'GradientColour' is not defined  # image 4
NameError: name 'GreyscaleMeanColour' is not defined # image 6
NameError: name 'LineUnionModifier' is not defined # image 9

I am using google colab.
Any advice?

Thanks in advance, JL

**Comment by lucashadfield** [comment]
you need to import those classes:
```python
from speck import GradientColour, GreyscaleMeanColour
from speck.modifier import LineUnionModifier
```
