### ISSUE TITLE
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

### ISSUE THREAD

**Issue by 825i** [lucashadfield/speck#5]
Whenever I try to use the program, no matter what image I try to use I get this error:

`SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape`

**Comment by lucashadfield** [comment]
I'm assuming this is in the input path string. If you're using windows you might have to escape the back slashes:

https://stackoverflow.com/questions/62339837/python-syntaxerror-unicode-error-unicodeescape-codec-cant-decode-bytes-in

**Comment by 825i** [comment]
Whoops that's embarrassing!

**Comment by flutterq** [comment]
all possible working solution added [[Solved] SyntaxError: (unicode error) ‘unicodeescape’ codec can’t decode bytes in position 2-3: truncated \UXXXXXXXX escape
](https://flutterq.com/syntaxerror-unicode-error-unicodeescape-codec-cant-decode-bytes-in-position-2-3-trunca/)
